version: 2.1

executors:
    node-executor:
        docker:
            - image: circleci/node:12
              environment:
                  CI: true

orbs:
    node: circleci/node@4.0.1

jobs:
    mobx-build:
        executor: node-executor
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn

            - run: yarn mobx build
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./*

    mobx-check:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run: yarn mobx test:check

    mobx-performance:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run:
                  command: yarn mobx test:performance
                  environment:
                      PERSIST: true
            - store_artifacts:
                  path: packages/mobx/perf_report
                  destination: mobx-perf

    mobx-coverage:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run: yarn mobx test:coverage
            - store_artifacts:
                  path: packages/mobx/coverage
                  destination: mobx-coverage
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./*

    mobx-size:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .

            - run: yarn mobx test:size

    # upload coverage
    mobx-coveralls:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .

            # only run coveralls if the token is present (it is not present for fork PRs for security reasons)
            - run:
                  name: upload coveralls
                  command: |
                      if [[ -v COVERALLS_REPO_TOKEN ]]
                      then
                          cat ./packages/mobx/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
                          echo "Coveralls info uploaded"
                      else
                          echo "Warning - Coveralls info could NOT be uploaded since the COVERALLS_REPO_TOKEN was not available"
                      fi

    mobx-undecorate-test:
        executor: node-executor
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run: yarn mobx-undecorate test

workflows:
    version: 2
    mobx:
        jobs:
            - mobx-build
            - mobx-check:
                  requires:
                      - mobx-build
            - mobx-performance:
                  requires:
                      - mobx-build
            - mobx-coverage:
                  requires:
                      - mobx-build
            - mobx-size:
                  requires:
                      - mobx-build
            - mobx-coveralls:
                  requires:
                      - mobx-coverage
    mobx-undecorate:
        jobs:
            - mobx-undecorate-test